language: ruby
cache: bundler
rvm:
- 2.1
addons:
  ssh_known_hosts:
  - engnroom.org
  - ftp.greenhost.nl
before_install:
- openssl aes-256-cbc -K $encrypted_7be9133180c7_key -iv $encrypted_7be9133180c7_iv
  -in deploy-key-library.enc -out deploy-key-library -d
- chmod 600 ~/.ssh/config
- chmod 600 deploy-key-library
- mv deploy-key-library ~/.ssh/id_rsa
- rm deploy-key-library.enc
- echo -e "Host engnroom.org" >> ~/.ssh/config
- echo -e "IdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config
- echo -e "Host ftp.greenhost.nl" >> ~/.ssh/config
- echo -e "IdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config
script:
- bash script/build.sh
after_success:
- bash script/deploy.sh
branches:
  only:
  - gh-pages
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
